#!/bin/bash
#This shebang is for synax only. Do not make executable!

_export () { export $1=$2; }

_export PROG    $(basename $0)
_export META    MYENV_BCH_MONTY
_export ROOT    $(mydts uniq -r ${META})
_export DST     ${ROOT}/repo
_export SRC     https://github.com/magicmonty/bash-git-prompt
_export SCRIPT  ${DST}/gitprompt.sh

usage () {
cat << EOF
USAGE:
        $PROG SUBCOMMAND

SUBCOMMANDS:
        install             -- clone MONTY to the tagged dir
        reinstall           -- reclone.
        activation          -- echo 'source <path>' to eval
        activation-script   -- echo the path to the activation script

DESCRIPTION:
        A front end to the 'magic-monty' prompt. Allows downloading
        and activation via a tagged dir.

SEE ALSO:
        bch_monty -h
EOF
}

msg () {
   >&2 echo "[${PROG}]: $*"
}


case $1. in
    .|-h|--help.)
        usage
        ;;
esac

[ -z ${ROOT} ] && msg "Could not resolve [${META}]."
[ -z ${ROOT} ] && exit 66

case $1. in
    install.)
        [ -d ${DST} ] && [ "$2" = "-v" ] && msg "already installed"
        [ -d ${DST} ] && exit
        git clone ${SRC} ${DST}
        ;;
    reinstall.)
        rm -rf ${DST}
        git clone ${SRC} ${DST}
        ;;
    uninstall.)
        rm -rf ${DST}
        ;;
    activation-script.)
       script=${DST}/gitprompt.sh
       [ -f $script ] && echo $script
       [ -f $script ] && exit
       msg "Activation script missing. Reinstall?"
       ;;
esac
